// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CGMZ_Core","status":true,"description":"Core CGMZ Plugin, should be placed above all other CGMZ Plugins.","parameters":{"Check for Updates":"true","Dev Tools on Start":"false","Fullscreen":"false","Force Locale":"","Fallback Locale":"en-US","CGMZ Defaults":"","Scroll Speed":"1","Scroll Wait":"300","Scroll Deceleration":"0.92","Auto Scroll":"true","CGMZ Controls":"","Scroll Up":"w","Scroll Down":"s","Playtest Options":"","Simulate Xbox Controller":"false","Simulate Playstation Controller":"false","Simulate Nintendo Controller":"false"}},
{"name":"CGMZ_SplashScreen","status":true,"description":"Creates a splash screen before the title screen","parameters":{"Skip In Playtest":"false","Stop BGM After Splash":"true","Splashes":"[\"{\\\"Image\\\":\\\"battlebacks1/Splash_1\\\",\\\"Center Image\\\":\\\"true\\\",\\\"Scale Image\\\":\\\"true\\\",\\\"Video\\\":\\\"\\\",\\\"Display Time\\\":\\\"240\\\",\\\"Fade In Time\\\":\\\"30\\\",\\\"Fade Out Time\\\":\\\"30\\\",\\\"Sound Effect\\\":\\\"\\\",\\\"BGM\\\":\\\"\\\",\\\"Sound Delay\\\":\\\"0\\\",\\\"Unskippable\\\":\\\"false\\\"}\"]"}}
];
